### ISSUE TITLE
2.1.1的填空题，似乎不太灵

### ISSUE THREAD

**Issue by q8195438** [XiangyuTang/LearnChinaHelper#16]

**Comment by q8195438** [comment]
会反复的弹出答案界面，并不输入任何字符

**Comment by XiangyuTang** [comment]
嗯嗯我也发现了这个问题，请问你是否升级了学习强国版本？

会反复的弹出答案界面，并不输入任何字符

**Comment by q8195438** [comment]
> 嗯嗯我也发现了这个问题，请问你是否升级了学习强国版本？ 会反复的弹出答案界面，并不输入任何字符 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

学习强国现在是2.11.0

**Comment by XiangyuTang** [comment]
我正在测试是否是由于学习强国版本更新的原因导致的问题，我正在回退版本为2.10.0测试
在2020年4月1日 01:15，FYF<notifications@github.com> 写道：

嗯嗯我也发现了这个问题，请问你是否升级了学习强国版本？ 会反复的弹出答案界面，并不输入任何字符 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

学习强国现在是2.11.0

**Comment by q8195438** [comment]
> 国版本更新的原因导致的问题，我正在回退版本为2.10.0测试 在2020年4月1日 01:15，FYF<notifications@github.com> 写道： 嗯嗯我也发现了这个问题，请问你是否升级了学习强国版本？ 会反复的弹出答案界面，并不输入任何字符 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 学习强国现在是2.11.0

辛苦了！

**Comment by XiangyuTang** [comment]
已发现问题，学习强国的题目内容控件排列已发生变化，正在尝试紧急修复。
在2020年4月1日 01:18，FYF<notifications@github.com> 写道：

国版本更新的原因导致的问题，我正在回退版本为2.10.0测试 在2020年4月1日 01:15，FYFnotifications@github.com 写道： 嗯嗯我也发现了这个问题，请问你是否升级了学习强国版本？ 会反复的弹出答案界面，并不输入任何字符 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 学习强国现在是2.11.0

辛苦了！

**Comment by q8195438** [comment]
如果这样的话，是否有一种方式来更加稳定的定位控件呢

**Comment by q8195438** [comment]
> 已发现问题，学习强国的题目内容控件排列已发生变化，正在尝试紧急修复。 在2020年4月1日 01:18，FYF<notifications@github.com> 写道： 国版本更新的原因导致的问题，我正在回退版本为2.10.0测试 在2020年4月1日 01:15，FYFnotifications@github.com 写道： 嗯嗯我也发现了这个问题，请问你是否升级了学习强国版本？ 会反复的弹出答案界面，并不输入任何字符 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 学习强国现在是2.11.0 辛苦了！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

如果这样的话，是否有一种方式来更加稳定的定位控件呢

**Comment by XiangyuTang** [comment]
这个应该是无法预测的，我看了一下，应该是填空题的题目内容控件嵌套顺序发生了变化，也就是说学习强国开发人员变更了控件的顺序，而这些控件将来如何变更我们预测不到，但是取得内容是需要准确的定位控件的位置的
在2020年4月1日 01:41，FYF<notifications@github.com> 写道：

已发现问题，学习强国的题目内容控件排列已发生变化，正在尝试紧急修复。 在2020年4月1日 01:18，FYFnotifications@github.com 写道： 国版本更新的原因导致的问题，我正在回退版本为2.10.0测试 在2020年4月1日 01:15，FYFnotifications@github.com 写道： 嗯嗯我也发现了这个问题，请问你是否升级了学习强国版本？ 会反复的弹出答案界面，并不输入任何字符 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 学习强国现在是2.11.0 辛苦了！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

如果这样的话，是否有一种方式来更加稳定的定位控件呢

**Comment by XiangyuTang** [comment]
已紧急修复，请测试v2.1.2版本

**Comment by q8195438** [comment]
> 已紧急修复，请测试v2.1.2版本

收到

**Comment by q8195438** [comment]
> 已紧急修复，请测试v2.1.2版本

填空题部分已经能够正常获得控件内容，但刚刚出现了一个匪夷所思的bug。

位于浙江省宁波市的（)是中国现存最早的私家藏书楼，也是亚洲现有最古老的图书馆和世界最早的三大家族图书馆之一。

这道题在处理答案的时候，答案匹配到了  私家藏  三个字

**Comment by XiangyuTang** [comment]
嗯嗯，由于填空题匹配机制的原因，这个结果是正常的。因为填空题的匹配机制是先找到题目内容中的空格，然后将空格的前后缀的3个字符带入题目中进行匹配，比如那个题，题干的空格前缀可能是“波市的”3个字，然后会带入提示中，可能提示的内容是“位于浙江省宁波市的私家藏书楼是XXX”，所以它就锁定到了“私家藏”。

**Comment by q8195438** [comment]
> 嗯嗯，由于填空题匹配机制的原因，这个结果是正常的。因为填空题的匹配机制是先找到题目内容中的空格，然后将空格的前后缀的3个字符带入题目中进行匹配，比如那个题，题干的空格前缀可能是“波市的”3个字，然后会带入提示中，可能提示的内容是“位于浙江省宁波市的私家藏书楼是XXX”，所以它就锁定到了“私家藏”。

好的，谢谢！
